### ISSUE TITLE
Why your test accuracy is lower than 90% with vanilla Resnet50?

### ISSUE THREAD

**Issue by gregary** [unsky/mixup#1]
The implementation of vanilla resnet 50 get 93%+ on cifar10 without mixup.
https://github.com/kuangliu/pytorch-cifar

**Comment by unsky** [comment]
The symbol of resnet50  is writen by  mxnet  https://github.com/apache/incubator-mxnet/tree/master/example/image-classification/symbols, there have many versions.  And i havenot do any
optimizion for it.  All the results  are based on this  baseline.

**Comment by gregary** [comment]
I reread the Resnet paper http://cn.arxiv.org/pdf/1512.03385.pdf.
On cifar 10,ResNet-44 gets 7.17% error, ResNet-56  gets 6.97% error in this paper.
So, I think resnet-50 baseline should be close to  93%. 
If your baseline is too low with the claimed accuracy, I think the comparision is not confident.

**Comment by unsky** [comment]
i will have a try on other resnet version in mxnet office example.  thx for your suggestion.
